const question = document.querySelector('#question')
const choices = Array.from(document.querySelectorAll('.choice-text'))
const progressText = document.querySelector('#progressText')
const scoreText = document.querySelector('#score')
const progressBarFull = document.querySelector('#progressBarFull')

let currentQuestion = {}
let acceptingAnswers = true
let score = 0
let questionCounter = 0
let availableQuestions = []


function showMe() {
    document.getElementById('donateMe').innerHTML = "09565796759(GCASH)"
}

    



let questions = [
    {
        question: 'Who was the literary figure known as “Huseng Sisiw”?',
        choice1: "Francisco Baltazar",
        choice2: "Jose de la Cruz",
        choice3: "Juan Matapang Cruz",
        choice4: "Jose Rizal",
        answer: 2,
    },
    {
        question: "That hard work has its rewards appears to be the _____ of the story.",
        choice1: "Moral",
        choice2: "Moralism",
        choice3: "Morality",
        choice4: "Morale",
        answer: 1,
    },
    {
        question: 'Simplify: 3(x - 4y) - (4y - 3x) - (2x -y)?',
        choice1: "4x - 17y",
        choice2: "-4x + 17 y",
        choice3: "4x - 17y",
        choice4: "-4x - 17y",
        answer: 3,
    },
    {
        question: 'What is considered as the earliest form of writing in the Philippines?',
        choice1: "Alibata",
        choice2: "Balitaw",
        choice3: 'Abakada',
        choice4: "Kalantiaw",
        answer: 1,
    },
    {
        question: 'Ayon sa diin sa pangtig ng salitang PITÓ, anong nais tukuyin ng kahulugan nito?',
        choice1: "Pangalan",
        choice2: "Bilang",
        choice3: "Silbato",
        choice4: "Lugar",
        answer: 2,
    },
    {
        question: 'Uri ng pangatnig na gamit sa pagpili, pagbubukod at pagtatangi.',
        choice1: "Paninsay",
        choice2: "Panlinaw",
        choice3: "Pamukod",
        choice4: "Panapos",
        answer: 3,
    },
    {
        question: 'Kailan nagsimula ang pagkakaroon ng modernisasyon ng wikang pambansa?',
        choice1: "1997",
        choice2: "1974",
        choice3: "1988",
        choice4: "1987",
        answer: 4,
    },
    {
        question: '“Pahalagahan ang pangaral ______ hindi malihis ng landas.” Anong pangatnig ang angkop sa pahayag na ito?',
        choice1: "Sakali",
        choice2: "Hait",
        choice3: "Nang",
        choice4: "Habang",
        answer: 3,
    },
    {
        question: 'Who was the Spanish governor-general who established the “tobacco monopoly” in 1781?',
        choice1: "Basilio Austin",
        choice2: "Jose Basco",
        choice3: "Rafael Izquierdo",
        choice4: "Francisco Rizzo",
        answer: 2,
    },
    {
        question: '“Huwag makisama sa Zoilo dahil buwaya siya.” Ang salitang buwaya ay tumutukoy sa kahulugang______.',
        choice1: "Etimolohiya",
        choice2: "Pampanitikan",
        choice3: "Denotasyon",
        choice4: "Konotasyon",
        answer: 4,
    },
    {
        question: 'All right angles are ______.',
        choice1: "Parallel",
        choice2: "Equal",
        choice3: "Oblique",
        choice4: "Supplementary",
        answer: 2,
    },
    {
        question: 'Ang pagpapalitan ng mga ideya, opinion, salaysay sa pamamagitang ng mga sagisag ay tinatawag na______.',
        choice1: "Pagtuklas",
        choice2: "Pakikinig",
        choice3: "Paglalahad",
        choice4: "Talastasan",
        answer: 4,
    },
    {
        question: 'After _____ all day, father finally found the time to rest.',
        choice1: "Having worked",
        choice2: "Working",
        choice3: "Had worked",
        choice4: "Have worked ",
        answer: 2,
    },
    {
        question: 'The empty board _____ on the table.',
        choice1: "Was leaving",
        choice2: "Were leaving",
        choice3: "Were left",
        choice4: "Was left",
        answer: 4,
    },
    {
        question: "Isang uri ng tsanel ng komunikasyon na gamit ang computer at iba't ibang network.",
        choice1: "Website",
        choice2: "Router",
        choice3: "Software",
        choice4: "Internet",
        answer: 4,
    },
    {
        question: 'Governor-General Narciso Claveria was responsible for the _______.',
        choice1: "Abolition of the Galleon Trade",
        choice2: "Establishment of the Tobacco Monopoly",
        choice3: "Use of Spanish surname by Filipinos",
        choice4: "Establishment of Galleon Trade",
        answer: 3,
    },
    {
        question: 'Drama _____ to be the most interesting co-curricular activity of the year.',
        choice1: "Appearing",
        choice2: "Appears",
        choice3: "Are appearing",
        choice4: "Appear",
        answer: 2,
    },
    {
        question: 'Which of the following classroom practices would be likely to increase retention?',
        choice1: "Organized materials according to shared attributes instead of objects means",
        choice2: "Structure materials without using topic sentences",
        choice3: "Present many general questions before introducing new materials",
        choice4: "Ask many questions following the presentation of new information",
        answer: 1,
    },
    {
        question: 'Saan kabilang na uri ng tayutay ang pahayag na: “Kapalaran, huwag ka sanang mailap.”',
        choice1: "Pagtawag",
        choice2: "Palit-saklaw",
        choice3: "Pagmamalabis",
        choice4: "Palit-tawag",
        answer: 1,
    },
    {
        question: 'What is the art and science that deals with the morality of human acts?',
        choice1: "Axiology",
        choice2: "Ethics",
        choice3: "Aesthetics",
        choice4: "Logic",
        answer: 2,
    },
    {
        question: 'Nakikipag-away sa speaker. Ito ay pakikinig na ______.',
        choice1: "Pasibo",
        choice2: "Masusi",
        choice3: "May hugod",
        choice4: "Kombatib",
        answer: 4,
    },
    {
        question: 'Who is considered as the Father of Iloco Literature?',
        choice1: "Pedro Bucaneg",
        choice2: "Pedro Paterno",
        choice3: "Francisco Balagtas",
        choice4: "Juan Crisostomo Sotto",
        answer: 1,
    },
    {
        question: 'Baghad is to Iraq and ______ is to Syria.',
        choice1: "Yemen",
        choice2: "Jordan",
        choice3: "Turkey",
        choice4: "Damascus",
        answer: 4,
    },
    {
        question: 'What was the name of forced labor imposed during the Spanish regime?',
        choice1: "Recopilacion",
        choice2: "Bandala",
        choice3: "Servicio manual",
        choice4: "Polo",
        answer: 4,
    },
    {
        question: 'Which program application provide users with a mean to organize and present information through the use of text, numbers, graphs, sounds and visual images?',
        choice1: "Word processing",
        choice2: "Multimedia",
        choice3: "Spreadsheet",
        choice4: "Publisher",
        answer: 2,
    },
    {
        question: 'The human person is an individual self-concious being of incalculable value in himself. What does this imply?',
        choice1: "Every human person’s value is dependent on his situation in life.",
        choice2: "A human person once handicapped, aged and defenseless hence less inner value.",
        choice3: "He cannot be a mere interment of the society and of the state.",
        choice4: "He has value only in retardation to the community",
        answer: 3,
    },
    {
        question: "Many children _____ for a parent's affection",
        choice1: "Longing",
        choice2: "Longs",
        choice3: "Long",
        choice4: "Are longing",
        answer: 4,
    },
    {
        question: 'Social network services available through the computer is _____.',
        choice1: "i-pad",
        choice2: "Facebook ",
        choice3: "Wikipeda",
        choice4: "Google",
        answer: 2,
    },
    {
        question: 'Ang kahulugan ng: “My bank account is in the red.”',
        choice1: "Nanakawan",
        choice2: "Bale-wala",
        choice3: "Nakapag-ipon",
        choice4: "Malapit na maubos",
        answer: 4,
    },
    {
        question: 'The proposed project ______ within the budget of the school.',
        choice1: "Are appearing",
        choice2: "Is appearing",
        choice3: "Is",
        choice4: "Are",
        answer: 3,
    },
    {
        question: 'Uri ng pagsulat na ang pokus ay ang imahinasyon ng manunulat upang pukawin ang damdamin.',
        choice1: "Jornalistik",
        choice2: "Akademiko",
        choice3: "Malikhain",
        choice4: "Teknikal",
        answer: 3,
    },
    {
        question: 'Nakapandidiri ang asong kalye na ______.',
        choice1: "Dumihan",
        choice2: "Ma-dumi",
        choice3: "Madumi",
        choice4: "Dumumi",
        answer: 3,
    },
    {
        question: 'Technology _____ dramatically in the twenty-first century.',
        choice1: "Has improved",
        choice2: "Did improved",
        choice3: "Is improved",
        choice4: "Was improved",
        answer: 1,
    },
    {
        question: 'Ang mga pamilang na isahan, waluhan, animan ay pamilang na ______.',
        choice1: "Patakaran",
        choice2: "Palansak",
        choice3: "Patakda",
        choice4: "Panunuran",
        answer: 2,
    },
    {
        question: 'Many children ______ left to the care of relatives while the parents work.',
        choice1: "Are",
        choice2: "Is",
        choice3: "Has been",
        choice4: "Will be",
        answer: 1,
    },
    {
        question: 'She hurt _____ while she was slicing the onions.',
        choice1: "Himself",
        choice2: "Myself",
        choice3: "Ourselves",
        choice4: "Herself",
        answer: 4,
    },
    {
        question: 'Mr. Tolentino was concerned about the safety of motorists and so he issued circular containing ______ safety instructions.',
        choice1: "Himself",
        choice2: "Themselves",
        choice3: "His",
        choice4: "Their",
        answer: 3,
    },
    {
        question: "Nelson Mandela sacrificed so much in his life - family, friends, and big chunk of his life for things he believed in a democratic South Africa, with equal rights and a beacon of hope for the rest of the world.Nelson Mandela's dream for South Africa, which was realized, was ______.",
        choice1: "Cooperation",
        choice2: "Unity",
        choice3: "Democracy",
        choice4: "Supremacy",
        answer: 3,
    },
    {
        question: '“As far back as I can remember, our family had always been an extended one. Our grandmother was the mainstay in the family, the silent strength behind our mother who is her daughter.” The informal guide and honorary household chief in the extended family is the ______.',
        choice1: "Grandmother",
        choice2: "Mother",
        choice3: "Father",
        choice4: "Aunt",
        answer: 1,
    },
    {
        question: 'Shirley has not forgotten that she was betrayed by her best friend and carried such ______ in her deeply offended heart for a long time.',
        choice1: "Rancor",
        choice2: "Doubt",
        choice3: "Souvenir",
        choice4: "Offense",
        answer: 1,
    },
    {
        question: 'Even when her friends betray her, Perla bears no rancor in her heart because she is not ______.',
        choice1: "Embarrassed",
        choice2: "Consoled",
        choice3: "Bitter",
        choice4: "Insulted",
        answer: 3,
    },
    {
        question: 'Clara would read any book or magazines she could lay her hands on and read from cover to cover in out sitting. She is such a ______ reader.',
        choice1: "Tedious",
        choice2: "Serious",
        choice3: "Leisurely",
        choice4: "Voracious",
        answer: 4,
    },
    {
        question: 'A lot of water ______ needed to irrigate the parched land.',
        choice1: "Is",
        choice2: "Are being",
        choice3: "Is being",
        choice4: "Are",
        answer: 1,
    },
    {
        question: 'You _____ finished eating before we arrive.',
        choice1: "Have",
        choice2: "Should",
        choice3: "Have been",
        choice4: "Will have",
        answer: 4,
    },
    {
        question: "I can't find _________ calculator; may I use _________, Richard?",
        choice1: "my, yours",
        choice2: "my, his",
        choice3: "his, yours",
        choice4: "yours, mine",
        answer: 1,
    },
    {
        question: 'Of the following remarks from workers, which deserve a higher wage owing to effective speech that increases work efficiency?',
        choice1: "I have strong hands, willingness and honesty in work",
        choice2: "I have strong hands and I am a willing worker",
        choice3: "I like people and listen to respond to their opinions and needs",
        choice4: "I have work well and plan my work to accomplish more",
        answer: 2,
    },
    {
        question: 'Among the kinds of listening, which is the type that most students do in the classroom?',
        choice1: "For inspiration",
        choice2: "For information and ideas",
        choice3: 'For "escape"',
        choice4: "For enjoyment",
        answer: 2,
    },
    {
        question: 'In the speech process, which is concerned with amplifying and enriching the voice, using human amplifiers such as the nose, windpipe and chest?',
        choice1: "Resonation",
        choice2: "Inflection",
        choice3: "Inflection",
        choice4: "Articulation",
        answer: 1,
    },
    {
        question: "Because it will adversely affect the population's food supplies, the most DISADVANTAGEOUS source of energy is ____________.",
        choice1: "wind",
        choice2: "sun",
        choice3: "geothermal",
        choice4: "plants",
        answer: 4,
    },
    {
        question: 'Imprisoned for 27 years, Nelson Mandela realized his dream of a free and non-racial South Africa by forgiving his oppressors and negotiating in good faith for the peaceful transition to democracy. Nelson Mandela demonstrated his trait of',
        choice1: "friendliness",
        choice2: "determination",
        choice3: "forgiving",
        choice4: "loyalty",
        answer: 3,
    },
    {
        question: 'Filipino writer whose stories and poems depict Filipino-Spanish cultural beliefs and traditions.',
        choice1: 'Edilberto Tiempo',
        choice2: 'Bienvenido Santos',
        choice3: 'N.V.M. Gonzales',
        choice4: 'Nick Joaquin',
        answer: 4,
    },
    {
        question: '"To be or not to be" is the beginning of the soliloquy of __________.',
        choice1: 'Richard III',
        choice2: 'Julius Ceasar',
        choice3: 'Macbeth',
        choice4: 'Hamlet',
        answer: 4,
    },
    {
        question: 'Kailan nagsimula ang pagkakaroon ng modernisasyon ng wikang pambansa?',
        choice1: '1974',
        choice2: '1997',
        choice3: '1987',
        choice4: '1988',
        answer: 3,
    },
    {
        question: 'Ang mga salitang teka, saan, tena, dali ay nagtataglay ng ________.',
        choice1: 'asimilasyon',
        choice2: 'metatesis',
        choice3: 'pagkaltas',
        choice4: 'tono',
        answer: 1,
    },
    {
        question: 'Ano ang tumutukoy sa bilang ng pantig sa bawat taludtod ng tula?',
        choice1: 'Diin',
        choice2: 'Tugma',
        choice3: 'Sukat',
        choice4: 'Talinghaga',
        answer: 3,
    },
    {
        question: 'Tumutulong ito sa mga salitang nakakapagpag-iisa at may kahulugan. Kilala rin itong salitang-ugat.',
        choice1: 'Paglalapi',
        choice2: 'Malayang morpema',
        choice3: 'Di-malayang morpema',
        choice4: 'Morpemang leksikal',
        answer: 2,
    },
    {
        question: 'Ang pagpapalitan ng mga ideya, opinion, salaysay sa pamamagitan ng mga sagisag at tinatawag na _____________.',
        choice1: 'pagtuklas',
        choice2: 'paglalahad',
        choice3: 'talastasan',
        choice4: 'pakikinig',
        answer: 3,
    },
    {
        question: 'Wikang nabuo mula sa pangunahing wika ng isang lugar o lalawigan na kadalasang sinasalita sa ibang bayan ng naturang lugar.',
        choice1: 'Etnolek',
        choice2: 'Ekolek',
        choice3: 'Sosyalek',
        choice4: 'Dayalek',
        answer: 4,
    },
    {
        question: 'Alin sa mga sumusunod ang nararapat sa komunikasyon na pasulat?',
        choice1: 'Lakas ng boses',
        choice2: 'Maayos na pagpapalugit',
        choice3: 'Maliksing mga mata',
        choice4: 'Pagkibit ng balikat',
        answer: 2,
    },
    {
        question: 'Ang simbolong kumakatawan sa mga bagay at pangyayaring nais ipahayag ng tao sa kanyang kapwa ay ____________.',
        choice1: 'tunog',
        choice2: 'sining',
        choice3: 'bokabularyo',
        choice4: 'wika',
        answer: 4,
    },
    {
        question: 'Ano ang kalabang mortal ng pakikinig?',
        choice1: 'Talinghaga',
        choice2: 'Ingay',
        choice3: 'Okasyon',
        choice4: 'Oras',
        answer: 2,
    },
    {
        question: 'Ano ang pinakapayak na anyo ng salita na walang kahalong panglapi?',
        choice1: 'Ponema',
        choice2: 'Laguhan',
        choice3: 'Gitlapi',
        choice4: 'Salitang-ugat',
        answer: 4,
    },
    {
        question: 'Sa pangungusap na "Malakas and boses mo, "anong bahagi ng pangungusap ang salitang "malakas"?',
        choice1: 'Pandiwa',
        choice2: 'Pangatnig',
        choice3: 'Pang-uri',
        choice4: 'Panghalip',
        answer: 3,
    },
    {
        question: 'Ang katumbas na bigkas ng titik Q sa kasalukuyan ay: __________',
        choice1: 'ku',
        choice2: 'kuya',
        choice3: 'kuyu',
        choice4: 'kyu',
        answer: 4,
    },
    {
        question: 'Bahagi ng pananaliksik kung saan matatagpuan ang panimula, kaligiran ng pag-aaral at konseptuwal framework.',
        choice1: 'Kabanata I',
        choice2: 'Kabanata II ',
        choice3: 'Kabanata III ',
        choice4: 'Kabanata IV ',
        answer: 1,
    },
    {
        question: 'Anong paraan ng pagkuha ng balangkas ang ginagamitan ng sunud-sunod na tatlong tuldok para ipakita na may mga bahaging hindi na sinipi sa talata?',
        choice1: 'Sinopsis',
        choice2: 'Elipsis',
        choice3: 'Abstrak',
        choice4: 'Sintesis',
        answer: 2,
    },
    {
        question: 'Pahayag na pasaklaw na nabubuo sa pamamagitan ng personal na panlasa o pagpili',
        choice1: 'Probable generalization',
        choice2: 'Subjective generalization',
        choice3: 'Analytical generalization',
        choice4: 'Categorial generalization',
        answer: 2,
    },
    {
        question: 'Dulog pampanitikan na nagbibigay ng diin ng sariling panlasa ng bumabasa, Kilala rin ito bilang reader-response theory.',
        choice1: 'Antropolohiya',
        choice2: 'Impresyonista',
        choice3: 'Patalambuhay',
        choice4: 'Pansikolohiya',
        answer: 2,
    },
    {
        question: 'Layunin ng tagapagsalita na may malakas na "sense of humor"',
        choice1: 'manghikayat',
        choice2: 'manlibang',
        choice3: 'magpatibay',
        choice4: 'magkwento',
        answer: 2,
    },
    {
        question: 'Proseso ng paghahatid ng saloobin, opinion, karunungan sa pamamagitan ng makabuluhang tunog.',
        choice1: 'pakikinig',
        choice2: 'pagbabasa',
        choice3: 'pagsasalita',
        choice4: 'pagtatala',
        answer: 3,
    },
    {
        question: 'Nakikipag-away ka sa speaker. Ito ay pakikinig na ____________',
        choice1: 'masusi',
        choice2: 'pasibo',
        choice3: 'kombatib',
        choice4: 'may lugod',
        answer: 3,
    },
    {
        question: 'Paraan ng pagbasa na ginagamit kung ang akda ay mahirap unawain:',
        choice1: 'preview',
        choice2: 'muling-basa',
        choice3: 'masuri',
        choice4: 'kaswal',
        answer: 2,
    },
    {
        question: 'Mr. Lazarte had incurred the following expenses in his trips to the Mindanao islands; P3.200.00; P2.500.00 and P1,500.00. What percent of this total monthly budget P40.000.00 did he spend for this trip?',
        choice1: '35%',
        choice2: '18%',
        choice3: '30%',
        choice4: '20%',
        answer: 2,
    },
    {
        question: 'A recipe calls for 2 cups of milk for every 7 cups of flour. A chef will use 28 cups of flour, how many cups of milk must he have?',
        choice1: '10',
        choice2: '8',
        choice3: '12',
        choice4: '14',
        answer: 2,
    },
    {
        question: 'How many seconds are there in a 24-hour day?',
        choice1: '86,400',
        choice2: '1,690',
        choice3: '1,779',
        choice4: '84,600',
        answer: 1,
    },
    {
        question: 'What number must be subtracted from both numerator and denominator of the fraction 11/23 to give a fraction whose value is 2/5?',
        choice1: '4',
        choice2: '3',
        choice3: '2',
        choice4: '5',
        answer: 2,
    },
    {
        question: 'Among the given decimals, which is equivalent to 9%?',
        choice1: '0.009',
        choice2: '0.09',
        choice3: '0.9',
        choice4: '9.0',
        answer: 2,
    },
    {
        question: 'Simplify: 5-[2-(-4)+11-8]',
        choice1: '4',
        choice2: '9',
        choice3: '-4',
        choice4: '6',
        answer: 3,
    },
    {
        question: 'The sum of three consecutive integers is 123. What are the integers?',
        choice1: '42, 44, 46',
        choice2: '40, 41, 42',
        choice3: '39, 40, 41',
        choice4: '41, 43, 45',
        answer: 2,
    },
    {
        question: 'Total amount after adding 8% interest for 3 months of P6,000.00?',
        choice1: 'P11,500.00',
        choice2: 'P6,120.00',
        choice3: 'P10,500.00',
        choice4: 'P11,050.00',
        answer: 2,
    },
    {
        question: 'Which are the prime factors of 56?',
        choice1: '7, 4, 2',
        choice2: '14, 2, 2',
        choice3: '7, 8',
        choice4: '7, 2, 2, 2',
        answer: 4,
    },
    {
        question: 'If 50% of x is 20, what is 20% of x?',
        choice1: '16',
        choice2: '27',
        choice3: '8',
        choice4: '12',
        answer: 3,
    },
    {
        question: 'Interest at 8% for 3 months on P6.000.00',
        choice1: 'P150.00',
        choice2: 'P120.00 ',
        choice3: 'P50.00',
        choice4: 'P250.00',
        answer: 2,
    },
    {
        question: 'The Least Common Multiple (LCM) of 2, 3 and 4 is ___________.',
        choice1: '24',
        choice2: '14',
        choice3: '13',
        choice4: '12',
        answer: 4,
    },
    {
        question: 'The Greatest Common Factor (GCF) of 22, 15, 7 is ___________.',
        choice1: '1',
        choice2: '3',
        choice3: '2',
        choice4: '4',
        answer: 1,
    },
    {
        question: 'How many prime numbers are there between 1 and 100?',
        choice1: '25',
        choice2: '24',
        choice3: '23',
        choice4: '22',
        answer: 1,
    },
    {
        question: 'A Toyota car travelling at a rate of 70 km. per hour leaves the house 2 hours after a Kia car has left and overtakes it in 5 hours. At what rate was the Kia car travelling?',
        choice1: '20 kilometers per hour',
        choice2: '30 kilometers per hour',
        choice3: '40 kilometers per hour',
        choice4: '50 kilometers per hour',
        answer: 4,
    },
    {
        question: 'The largest common-factor of two or more numbers is called? ',
        choice1: 'Greatest common factor',
        choice2: 'Prime factor',
        choice3: 'Least common factor',
        choice4: 'Prime common factor',
        answer: 1,
    },
    {
        question: 'In a University, the ratio of female professors to the male professors is 8:5. If there are 75 male professors, how many are female professors?',
        choice1: '180',
        choice2: '120',
        choice3: '375/8',
        choice4: '225',
        answer: 2,
    },
    {
        question: 'Simplify: 6-[3-(4)+11 +8].',
        choice1: '26',
        choice2: '-26',
        choice3: '20',
        choice4: '-12',
        answer: 4,
    },
    {
        question: 'Which are the prime factors of 56?',
        choice1: '7, 2, 2, 2',
        choice2: '14, 2, 2',
        choice3: '7, 4, 2',
        choice4: '7, 8',
        answer: 1,
    },
    {
        question: 'The grades in Mathematics, of the students in section A are as follows: 80, 75, 60, 95, 100. What is the population variance of their group?',
        choice1: '230',
        choice2: '270',
        choice3: '264',
        choice4: '206',
        answer: 4,
    },
    {
        question: 'Which among the measures of central tendency is not influenced by outliers? ',
        choice1: 'Median',
        choice2: 'Weighted Mean',
        choice3: 'Mean',
        choice4: 'Mode',
        answer: 1,
    },
    {
        question: 'In how many ways can 5 girls be seated in a row of 5 seats?',
        choice1: '95',
        choice2: '100',
        choice3: '105',
        choice4: '120',
        answer: 4,
    },
    {
        question: 'If a die is rolled, what is the probability of getting a number divisible by 2?',
        choice1: '1/6',
        choice2: '1/4',
        choice3: '1/2',
        choice4: '1/3',
        answer: 3,
    },
    {
        question: 'Which of the following is a product of 13 and an integer?',
        choice1: '1326',
        choice2: '1323',
        choice3: '1343',
        choice4: '131',
        answer: 1,
    },
    {
        question: 'A rectangular block of steel has dimensions of 5 meters x 10 meters x 15 meters and weights, 1,000 N. How should this block be placed on a surface to exert the lease pressure on the surface? ',
        choice1: 'On the 10 meters by 15 meters side',
        choice2: 'On the 5 meters by 15 meters side',
        choice3: 'On the 5 meters by 10 meters side',
        choice4: 'All sides have equal pressure',
        answer: 1,
    },
    {
        question: 'If a student has an average of 76% on his first two tests, and has an average of 85% on the next four tests, what is his final average on all six tests?',
        choice1: '82.5%',
        choice2: '80.5%',
        choice3: '81.3%',
        choice4: '82.0%',
        answer: 4,
    },
    {
        question: 'What percent of 75 is 15?',
        choice1: '20%',
        choice2: '30%',
        choice3: '38%',
        choice4: '40%',
        answer: 1,
    },
    {
        question: 'Which of the following processes involves chloroplast?',
        choice1: 'Conversion of light energy to chemical energy',
        choice2: 'Formulation of reproductive cells',
        choice3: 'Cell division',
        choice4: 'Protein synthesis',
        answer: 1,
    },
    {
        question: "What is the term for the slowing-down response by the frog's circulatory during the cold season",
        choice1: 'Cold-blooded reaction',
        choice2: 'Temperature response',
        choice3: 'Hibernation',
        choice4: 'Estivation',
        answer: 3,
    },
    {
        question: 'Which of the following is a vitamin?',
        choice1: 'Niacin',
        choice2: 'Mucin',
        choice3: 'Pepsin',
        choice4: 'Trypsin',
        answer: 1,
    },
    {
        question: 'Which element has Ca as its symbol',
        choice1: 'Cadmium',
        choice2: 'Californium',
        choice3: 'Carbon',
        choice4: 'Calcium',
        answer: 4,
    },
    {
        question: 'Besides solid, liquid and gas, what is the fourth form of matter?',
        choice1: 'Plasma',
        choice2: 'Gel',
        choice3: 'Foam',
        choice4: 'Colloid',
        answer: 1,
    },
    {
        question: 'Which of the following is a heterotroph?',
        choice1: 'Moss',
        choice2: 'Grasshopper',
        choice3: 'Algae',
        choice4: 'Fern',
        answer: 2,
    },
    {
        question: 'Which type of reaction does the general equation (AB+energy->A+B) show?',
        choice1: 'Endothermic synthesis',
        choice2: 'Exothermic decomposition',
        choice3: 'Exothermic synthesis',
        choice4: 'Endothermic decomposition',
        answer: 4,
    },
    {
        question: 'Humans reproduce when an ovum is combined with a sperm leading to the development of an embryo.This form of reproduction is called________.',
        choice1: 'Binary fission',
        choice2: 'Asexual reproduction',
        choice3: 'Budding',
        choice4: 'Fertilization',
        answer: 4,
    },
    {
        question: 'Which of the following activities help reduce water pollution?',
        choice1: 'Use of soap and detergents',
        choice2: 'Desalination of sea water to potable water',
        choice3: 'Setting up flood control systems',
        choice4: 'Treating waste water prior to discharge',
        answer: 4,
    },
    {
        question: 'What is the main organ for respiration?',
        choice1: 'esophagus',
        choice2: 'lungs',
        choice3: 'nose',
        choice4: 'heart',
        answer: 2,
    },
    {
        question: 'What technology technique is employed during breeding in captivity in order to restore the populations of endangered and threatened species to safe levels?',
        choice1: 'Artificial insemination',
        choice2: 'Cobalt radiation',
        choice3: 'Cross pollination',
        choice4: 'Genetic engineering',
        answer: 1,
    },
    {
        question: 'What is the molecule that allows plants to capture energy from sunlight?',
        choice1: 'ATP',
        choice2: 'Oxygen',
        choice3: 'Carbohydrates',
        choice4: 'Chlorophyll',
        answer: 4,
    },
    {
        question: 'Dengue is an infectious disease transmitted by an organism classified under which phylum?',
        choice1: 'chordate',
        choice2: 'arthropoda',
        choice3: 'hemichordata',
        choice4: 'Echinodermata',
        answer: 2,
    },
    {
        question: 'What is unique feature of fungi?',
        choice1: 'They contain mitochondria',
        choice2: 'They contain genetic material',
        choice3: 'Some are capable of bioluminescence',
        choice4: 'They combined chitins and glucans in their cell wall',
        answer: 4,
    },
    {
        question: 'What diagnostic test allows microorganism to multiply in a medium under controlled laboratory condition in order to determine the cause of an infectious disease?',
        choice1: 'Microbial culture',
        choice2: 'Chest x-ray ',
        choice3: 'Urinalysis',
        choice4: 'Complete blood count',
        answer: 1,
    },
    {
        question: 'The union of an ovum and sperm inside a test tube is _________.',
        choice1: 'embryology',
        choice2: 'in vitro fertilization',
        choice3: 'in vivo fertilization',
        choice4: 'polination',
        answer: 2,
    },
    {
        question: 'What are the small hair-like structure that serve a sensory function in eukaryotic cells?',
        choice1: 'Cilia',
        choice2: 'Centromere',
        choice3: 'Actin filaments',
        choice4: 'Plasma membrane',
        answer: 1,
    },
    {
        question: 'Which of the following process best explains the evolution of life forms or gradual transformation of species?',
        choice1: 'New combination of genes',
        choice2: 'Natural selection',
        choice3: 'Isolation',
        choice4: 'Genetic drift',
        answer: 2,
    },
    {
        question: 'Which technology can lead to the formation of a new genetic trait?',
        choice1: 'Tissue culture',
        choice2: 'Embryo transplant',
        choice3: 'Exposure to radiation',
        choice4: 'Asexual reproduction',
        answer: 3,
    },
    {
        question: 'Which is an example of natural altered state of awareness?',
        choice1: 'Sedation',
        choice2: 'Intoxication',
        choice3: 'Sleep',
        choice4: 'Drug "high"',
        answer: 3,
    },
    {
        question: 'Which characterizes psychologically healthy people?',
        choice1: 'concerned with goals beyond themselves',
        choice2: 'feels superior over others',
        choice3: "can't accept others as they are",
        choice4: 'pre-occupied only with their interests',
        answer: 1,
    },
    {
        question: 'Who was the orator of the Reform Movement and first editor of La Solidaridad?',
        choice1: 'Jose Rizal',
        choice2: 'Marcelo del Pilar',
        choice3: 'Juan Luna',
        choice4: 'Graciano Lopez Jaena',
        answer: 4,
    },
    {
        question: 'Which is the fundamental law of the Philippines?',
        choice1: 'The Philippine Constitution',
        choice2: 'The Ten Commandments',
        choice3: 'The Civil and Crime Codes',
        choice4: 'The Bill of Rights',
        answer: 1,
    },
    {
        question: 'What law passed on August 1909 by the U.S Congress established a partial free foreign trade for the Philippines?',
        choice1: 'Underwood-Simmons Act',
        choice2: 'Bell Trade',
        choice3: 'Payne-Aldrich Act',
        choice4: 'Treaty of General Relations',
        answer: 3,
    },
    {
        question: 'Which state policy provides for preferential attention to the welfare of the less fortunate members of the Philippine society?',
        choice1: 'Bill of Rights',
        choice2: 'Social justice',
        choice3: 'Distributive justice',
        choice4: 'Criminal justice',
        answer: 2,
    },
    {
        question: 'Which condition contradicts the social justice mandated in the 1987 Constitution?',
        choice1: 'Sense of dependency among citizens',
        choice2: 'Creation of economic opportunities for all',
        choice3: 'Elimination of cultural inequalities',
        choice4: 'Equitable distribution of wealth',
        answer: 1,
    },
    {
        question: 'What is the term for the unpleasant sensation or frustration when a traditional-bound Filipino goes to the U.S and observes the open display of love and emotions?',
        choice1: 'Culture relativism',
        choice2: 'Culture cosmopolitanism',
        choice3: 'Culture shock',
        choice4: 'Culture phobia',
        answer: 3,
    },
    {
        question: 'One of the pledges of the President of the Philippines is to defend its:',
        choice1: 'Constitution',
        choice2: 'Land',
        choice3: 'Citizens',
        choice4: 'Islands',
        answer: 1,
    },
    {
        question: 'Which law set a full free trade policy abolishing the quota limitations on Philippine exports to the United States?',
        choice1: 'Payne-Aldrich Act',
        choice2: 'Underwood-Simmons Act',
        choice3: 'Hare-Hawes Cutting Act',
        choice4: 'Bell Trade',
        answer: 2,
    },
    {
        question: 'When one controls the supply/production of goods, this implies',
        choice1: 'inflation',
        choice2: 'economic stability',
        choice3: 'monopoly',
        choice4: 'economic equilibrium',
        answer: 3,
    },
    {
        question: 'Which enacted by the U.S Congress in 1916 established a bicameral legislature in the Philippines with the senator (upper House) and House of Representative (Lower house)to be composed of elected Filipinos?',
        choice1: 'Philippine Legislative Law',
        choice2: 'McKinley Law',
        choice3: 'Cooper Act',
        choice4: 'Jones law',
        answer: 4,
    },
    {
        question: 'What is considered the earliest form of writing in the Philippines?',
        choice1: 'Alibata',
        choice2: 'Kalantiao',
        choice3: 'Abakada',
        choice4: 'Balitaw',
        answer: 1,
    },
    {
        question: 'During the 17-18th century Hispanic era, what was the highest post a native‘ or Chinese-mestizo can attain at the municipal level, equivalent to local bureaucrats namely the mayors today?',
        choice1: 'Governadorcillo',
        choice2: 'Tanientes de justicia',
        choice3: 'Cabeza de barangay',
        choice4: 'Directorcillo',
        answer: 1,
    },
    {
        question: 'During the Hispanic era, native and Chinese male mestizo 16-60 years old are obliged do forced labor for forty day. How can exemption be made?',
        choice1: 'Getting a cedula personal',
        choice2: 'Give santorum tax to the church',
        choice3: 'Paying the bandala',
        choice4: 'Paying the falla (exemption fee)',
        answer: 4,
    },
    {
        question: 'Which Spanish policy provided the resettlement of Filipino communities to form town centers of cabeceras?',
        choice1: 'Assimilation',
        choice2: 'Esseminda system',
        choice3: 'Reduccion',
        choice4: 'Bandala',
        answer: 3,
    },
    {
        question: 'Art is the handmaid of religion. Why do Jews and Muslims allow signs and symbols and not human beings in religious art?',
        choice1: 'People might worship images themselves',
        choice2: 'Signs and symbols display hidden mysteries',
        choice3: 'Human figures are difficult art forms',
        choice4: 'They display more traditional themes',
        answer: 1,
    },
    {
        question: 'Taoism is another Chinese philosophy about the same period as Confucianism; but more spiritual rather than ethical interest as it stressed that nature contains a divine impulse that directs all life. Who is the philosopher behind Taoism?',
        choice1: 'Confucius',
        choice2: 'Lao-Tzu',
        choice3: 'The Buddha',
        choice4: 'Sidharta Gautama',
        answer: 2,
    },
    {
        question: 'Due to close family ties, Filipino families are generally',
        choice1: 'nuclear',
        choice2: 'extended',
        choice3: 'divided',
        choice4: 'secular',
        answer: 2,
    },
    {
        question: 'What contained the concrete promise of the Americans to Filipinos independence "as soon as stable government can be established"?',
        choice1: 'Preamble of the Jones Law',
        choice2: 'Fairfield Bill of 1924',
        choice3: 'Preamble of the Commonwealth Government',
        choice4: 'First 1919 Parliamentary Mission to the U.S',
        answer: 3,
    },
    {
        question: 'What symbol is used to make the text bold?',
        choice1: 'Ctrl + X',
        choice2: 'Ctrl + 0',
        choice3: 'Ctrl + B',
        choice4: 'Ctrl + V',
        answer: 3,
    },
    {
        question: '__________ means the graphics will be displayed more than once.',
        choice1: 'texting',
        choice2: 'timing',
        choice3: 'tiling',
        choice4: 'tagging',
        answer: 3,
    },
    {
        question: 'Which is the brain of the computer?',
        choice1: 'RAM',
        choice2: 'CPU',
        choice3: 'Program',
        choice4: 'Password',
        answer: 2,
    },
    {
        question: '“She is a lovely rose.” is _______.',
        choice1: 'Simile',
        choice2: 'Hyperbole',
        choice3: 'Irony',
        choice4: 'Metaphor',
        answer: 4,
    },
    {
        question: 'A story put together through an exchange of letter is called _____ literature.',
        choice1: 'Fiction',
        choice2: 'Epistolary',
        choice3: 'Episodic',
        choice4: 'Classic',
        answer: 2,
    },
    {
        question: 'Some preachers suggest the ____ that the end of the world is near.',
        choice1: 'Proposal',
        choice2: 'Prophetic',
        choice3: 'Prophecy',
        choice4: 'Prophet',
        answer: 3,
    },
    {
        question: 'The expression of “baduy” connotes:',
        choice1: 'Uneducated',
        choice2: 'Awkward looking',
        choice3: 'Low profile',
        choice4: 'Smart',
        answer: 2,
    },
    {
        question: '“Because of PROFANITY the program was suspended from television.” The capitalized word means?',
        choice1: 'Obscenity',
        choice2: 'History',
        choice3: 'Decency',
        choice4: 'Falsehood',
        answer: 1,
    },
    {
        question: 'What is the lowest form of learning?',
        choice1: 'Perceiving',
        choice2: 'Responding',
        choice3: 'Conditioning',
        choice4: 'Teaching',
        answer: 1,
    },
    {
        question: 'Which of the following is the study of human behavior?',
        choice1: 'Philosophy',
        choice2: 'Morality',
        choice3: 'Psychology',
        choice4: 'Ethics',
        answer: 3,
    },
    {
        question: 'Which of the following statements is true about textbook laid on the table?',
        choice1: 'No force is acting on it',
        choice2: 'The textbook undergoes acceleration',
        choice3: 'The sum of the forces acting upon it is zero',
        choice4: 'The textbook undergoes deceleration',
        answer: 3,
    },
    {
        question: 'Which of the following is an artistic tradition that seeks to revive past glory in various forms?',
        choice1: 'Antique',
        choice2: 'Modern',
        choice3: 'Contemporary',
        choice4: 'Classical',
        answer: 4,
    },
]

const SCORE_POINTS = 1
const MAX_QUESTIONS = 150

startGame = () => {
    questionCounter = 0
    score = 0
    availableQuestions = [...questions]
    getNewQuestion()
}

getNewQuestion = () => {
    if(availableQuestions.length === 0 || questionCounter > MAX_QUESTIONS) {
        localStorage.setItem('mostRecentScore', score)

        return window.location.assign('/end.html')
    }

    questionCounter++
    progressText.innerText = `Question ${questionCounter} of ${MAX_QUESTIONS}`
    progressBarFull.style.width = `${(questionCounter/MAX_QUESTIONS) * 100}%`

    const questionsIndex = Math.floor(Math.random() * availableQuestions.length)
    currentQuestion = availableQuestions[questionsIndex]
    question.innerText = currentQuestion.question

    choices.forEach(choice => {
        const number = choice.dataset['number']
        choice.innerText = currentQuestion['choice' + number]

    })

    availableQuestions.splice(questionsIndex, 1)

    acceptingAnswers = true
}

choices.forEach(choice => {
    choice.addEventListener('click', e => {
        if(!acceptingAnswers) return

        acceptingAnswers = false
        const selectedChoice = e.target
        const selectedAnswer = selectedChoice.dataset ['number']

        let classToApply = selectedAnswer == currentQuestion.answer ? 'correct' : 'incorrect'

        if(classToApply === 'correct') {
            incrementScore(SCORE_POINTS)
        }

        selectedChoice.parentElement.classList.add(classToApply)

        setTimeout(() => {
            selectedChoice.parentElement.classList.remove(classToApply)
            getNewQuestion()

        }, 1000)
    })
})

incrementScore = num => {
    score +=num
    scoreText.innerText = score
}

startGame()